@baseUrl = http://localhost:8000
@api=/api


#### register auth
POST {{baseUrl}}{{api}}/register
Content-Type: application/json
Accept: application/json

{
    "name": "John Doe",
    "email": "ni1@gmail.com",
    "password":"123456",
    "password_confirmation":"123456"
}

#### login auth
POST {{baseUrl}}{{api}}/login
Content-Type: application/json
Accept: application/json

{
    "email": "ni@gmail.com",
    "password":"123456"
}

#### logout auth
POST {{baseUrl}}{{api}}/logout
Content-Type: application/json
Accept: application/json
Authorization: Bearer 6|C9NVHxGOoOwcu6gKMtMAug91JDJti4WBrZ7o8jhD809d572d



#### get all post
GET {{baseUrl}}{{api}}/posts
Accept: application/json



#### create new post
POST {{baseUrl}}{{api}}/posts
Content-Type: application/json
Accept: application/json
Authorization: Bearer 3|8VAM7QBOROrSkoOe7gsa5uTFTfTz5ByBmtlcMxwh86a6318a

{
  "title": "First Post",
  "body": "This is the body text"
}

#### update post
PATCH {{baseUrl}}{{api}}/posts/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 4|LiNsGQHwABmXrBwii8X0RL6w3gmxEoErFZVOkpxkdec7660f

{
  "title": "Updated Post",
  "body": "This is the body text"
}
